# Generated by Django 4.2.7 on 2023-11-22 23:20

from django.db import migrations, models
import django.db.models.deletion
import houses.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('beds', models.IntegerField(default=0)),
                ('baths', models.IntegerField(default=0)),
                ('sqft', models.IntegerField(default=0)),
                ('lot_size', models.IntegerField(default=0)),
                ('year_built', models.IntegerField(default=0)),
                ('property_type', models.CharField(max_length=200)),
                ('sale_type', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=houses.models.house_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=houses.models.house_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=houses.models.house_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=houses.models.house_image_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=houses.models.house_image_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=houses.models.house_video_path)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
