# Generated by Django 4.2.7 on 2023-11-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_address_alter_house_baths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
